Repository goharbor/harbor-operator, pull requests merged in 2020-12, with the labels that each got.

#244 Fix notary not shown on UI
  controllers/goharbor/harbor/core.go
Labels: release/0.6.0

#247 fix(trivy) failed pull image
  controllers/goharbor/core/deployments.go
Labels: release/0.6.0

#251 fix(database) fix postgres health check ping operation was canceled
  pkg/cluster/controllers/database/postgresql.go
  pkg/cluster/controllers/database/readiness.go
Labels: dependency/database

#262 feat(kustomize):use released versions of kus yamls
  manifests/cluster/deployment.yaml
  manifests/cluster/kustomization.yaml
  manifests/cluster/patch/annotations.yaml
Labels: area/kustomization

#282 fix(database) add psql- prefix to database pod name
  pkg/cluster/controllers/database/generate.go
Labels: dependency/database

#292 fix(minio): fix minio resource name
  pkg/cluster/controllers/storage/provision.go
Labels: area/storage, kind/bug

#298 feat(database) implement svc config getter
  controllers/goharbor/harborcluster/service_mgr.go
  controllers/goharbor/harborcluster/svc_config.go
Labels: dependency/database

#314 fix(database) failed to initialize database core
  config/samples/harborcluster/goharbor_v1alpha2_harborcluster.yaml
  pkg/cluster/controllers/database/generate.go
  pkg/cluster/controllers/database/readiness.go
  pkg/cluster/controllers/database/utils.go
Labels: dependency/database

#329 fix coreurl mismatch
  controllers/goharbor/harbor/jobservice.go
Labels: release/1.0

#328 fix encrypt key length to 16
  controllers/goharbor/harbor/core.go
Labels: release/1.0

#322 update harbor version to 2.1.2
  controllers/goharbor/chartmuseum/chartmuseum.go
  controllers/goharbor/core/core.go
  controllers/goharbor/jobservice/jobservice.go
  controllers/goharbor/notaryserver/notaryserver.go
  controllers/goharbor/notarysigner/notarysigner.go
  controllers/goharbor/portal/portal.go
  controllers/goharbor/registry/registry.go
  controllers/goharbor/registryctl/registryctl.go
  controllers/goharbor/trivy/trivy.go
  pkg/config/config.go
Labels: release/1.0

#332 fix(ctrl):update cluster ctrl for status timestamp
  controllers/goharbor/harborcluster/status.go
Labels: release/1.0

#334 fix(minio):update svcconfig getter
  controllers/goharbor/harborcluster/svc_config.go
Labels: release/1.0

#359 fix(notary) cert name too long
  controllers/goharbor/harbor/notarysigner.go
Labels: release/1.0

#358 add other dependencies in sample yaml
  manifests/samples/full_stack_other_fs.yaml
Labels: release/1.0
