Repository goharbor/harbor-operator, pull requests merged in 2020-04, with the labels that each got.

#34 docs(authors) Remove authors file. Fix #16.
  .github/CODEOWNERS
Labels: documentation, release/0.5

#33 docs(installation) Format documentation and fix command to install nginx-controller chart
  docs/installation.md
Labels: documentation

#32 a step-by-step install guide on KIND k8s
  docs/install-with-kind-k8s.md
Labels: area/installation, documentation, release/0.5

#49 fix(ci) New way to deploy CertManager CRDs
  .github/workflows/tests.yml
Labels: area/CICD, bug

#52 fix(cd) Use only version part from ${{ github.ref }} as docker tag
  .github/workflows/release.yml
Labels: area/CICD, bug, release/0.5
