Repository goharbor/harbor-operator, pull requests merged in 2020-11, with the labels that each got.

#171 Feature/migration harbor cluster spec
  apis/goharbor.io/v1alpha2/harborcluster_types.go
  apis/goharbor.io/v1alpha2/zz_generated.deepcopy.go
  config/samples/harborcluster/goharbor_v1alpha2_harborcluster.yaml
  controllers/controller_string.go
  controllers/controllers.go
  controllers/goharbor/controller_test.go
  controllers/goharbor/harborcluster/cache/redis.go
  controllers/goharbor/harborcluster/database/postgresql.go
  controllers/goharbor/harborcluster/harbor/harbor.go
  controllers/goharbor/harborcluster/harborcluster_controller.go
  controllers/goharbor/harborcluster/resources.go
  controllers/goharbor/harborcluster/service.go
  controllers/goharbor/harborcluster/storage/minio.go
  go.mod
  pkg/image/harbor_v1.10.0.go
  pkg/image/harbor_v1.10.x.go
  pkg/image/image.go
  pkg/k8s/client.go
  pkg/k8s/dynamic.go
  pkg/k8s/labels.go
  pkg/lcm/lcm.go
  pkg/lcm/property.go
  pkg/lcm/property_test.go
  pkg/setup/controllers.go
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  vendor/modules.txt
Labels: area/reconciler

#189 feat: add cache(redis) controller
  config/samples/harborcluster/goharbor_v1alpha2_harborcluster.yaml
  controllers/goharbor/harborcluster/harborcluster_controller.go
  go.mod
  go.sum
  pkg/cluster/cache/constants.go
  pkg/cluster/cache/deploy.go
  pkg/cluster/cache/readiness.go
  pkg/cluster/cache/redis.go
  pkg/cluster/cache/redis_connect.go
  pkg/cluster/cache/resource_manager.go
  pkg/cluster/cache/update.go
  pkg/cluster/cache/utils.go
  vendor/github.com/go-redis/redis/.gitignore
  vendor/github.com/go-redis/redis/.travis.yml
  vendor/github.com/go-redis/redis/CHANGELOG.md
  vendor/github.com/go-redis/redis/LICENSE
  vendor/github.com/go-redis/redis/Makefile
  vendor/github.com/go-redis/redis/README.md
  vendor/github.com/go-redis/redis/cluster.go
  vendor/github.com/go-redis/redis/cluster_commands.go
  vendor/github.com/go-redis/redis/command.go
  vendor/github.com/go-redis/redis/commands.go
  vendor/github.com/go-redis/redis/doc.go
  vendor/github.com/go-redis/redis/internal/consistenthash/consistenthash.go
  vendor/github.com/go-redis/redis/internal/error.go
  vendor/github.com/go-redis/redis/internal/hashtag/hashtag.go
  vendor/github.com/go-redis/redis/internal/internal.go
  vendor/github.com/go-redis/redis/internal/log.go
  vendor/github.com/go-redis/redis/internal/once.go
  vendor/github.com/go-redis/redis/internal/pool/conn.go
  vendor/github.com/go-redis/redis/internal/pool/pool.go
  vendor/github.com/go-redis/redis/internal/pool/pool_single.go
  vendor/github.com/go-redis/redis/internal/pool/pool_sticky.go
  vendor/github.com/go-redis/redis/internal/proto/reader.go
  vendor/github.com/go-redis/redis/internal/proto/scan.go
  vendor/github.com/go-redis/redis/internal/proto/writer.go
  vendor/github.com/go-redis/redis/internal/util.go
  vendor/github.com/go-redis/redis/internal/util/safe.go
  vendor/github.com/go-redis/redis/internal/util/strconv.go
  vendor/github.com/go-redis/redis/internal/util/unsafe.go
  vendor/github.com/go-redis/redis/iterator.go
  vendor/github.com/go-redis/redis/options.go
  vendor/github.com/go-redis/redis/pipeline.go
  vendor/github.com/go-redis/redis/pubsub.go
  vendor/github.com/go-redis/redis/redis.go
  vendor/github.com/go-redis/redis/result.go
  vendor/github.com/go-redis/redis/ring.go
  vendor/github.com/go-redis/redis/script.go
  vendor/github.com/go-redis/redis/sentinel.go
  vendor/github.com/go-redis/redis/tx.go
  vendor/github.com/go-redis/redis/universal.go
  vendor/github.com/spotahome/redis-operator/LICENSE
  vendor/github.com/spotahome/redis-operator/api/redisfailover/register.go
  vendor/github.com/spotahome/redis-operator/api/redisfailover/v1/defaults.go
  vendor/github.com/spotahome/redis-operator/api/redisfailover/v1/doc.go
  vendor/github.com/spotahome/redis-operator/api/redisfailover/v1/register.go
  vendor/github.com/spotahome/redis-operator/api/redisfailover/v1/types.go
  vendor/github.com/spotahome/redis-operator/api/redisfailover/v1/validate.go
  vendor/github.com/spotahome/redis-operator/api/redisfailover/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: component/cache, dependency/cache

#214 feat(kustomization): add kustomization manifests
  config/crd/patches/cainjection_in_harborclusters.yaml
  config/crd/patches/webhook_in_harborclusters.yaml
  manifests/README.md
  manifests/cluster/README.md
  manifests/cluster/deployment.yaml
  manifests/cluster/kustomization.yaml
  manifests/cluster/patch/namespace.yaml
  manifests/harbor/README.md
  manifests/harbor/deployment.yaml
  manifests/harbor/kustomization.yaml
  manifests/harbor/namespace.yaml
Labels: area/kustomization

#228 refactor(main): refactor main.go to reduce duplicate code
  main.go
  pkg/setup/setup.go
Labels: refactor

#230 enable github security scan
  .github/workflows/codeql-analysis.yml
Labels: area/security
