Repository goharbor/harbor-operator, pull requests merged in 2021-05, with the labels that each got.

#632 doc(backup):add notes to the backup docs
  docs/LCM/backup-minio-data.md
  docs/LCM/backup-psql-data.md
  docs/LCM/backup-redis-data.md
Labels: documentation, release/1.0

#656 fix(version) notaryserver.go
  controllers/goharbor/harbor/notaryserver.go
Labels: release/1.1

#657 [cherry-pick ]fix(version) notaryserver.go 1.0.1
  controllers/goharbor/harbor/notaryserver.go
Labels: release/1.0.1

#659 [cherry-pick] Add contour support 1.0.1
  .github/workflows/tests.yml
  apis/goharbor.io/v1alpha3/harbor_types.go
  apis/meta/v1alpha1/ingress_controller.go
  controllers/goharbor/core/services.go
  controllers/goharbor/harbor/core.go
  controllers/goharbor/harbor/ingresses.go
  controllers/goharbor/harbor/notaryserver.go
  controllers/goharbor/harbor/portal.go
  controllers/goharbor/notaryserver/services.go
  controllers/goharbor/portal/services.go
  manifests/cluster/deployment.yaml
  manifests/harbor/deployment.yaml
  manifests/samples/full_stack.yaml
  manifests/samples/minimal_stack_fs.yaml
  manifests/samples/minimal_stack_incluster.yaml
  manifests/samples/standard_stack.yaml
  manifests/samples/standard_stack_fs.yaml
  pkg/cluster/controllers/common/utils.go
  pkg/cluster/controllers/storage/ingress.go
Labels: release/1.0.1

#663 [Cherry pick]feat: support the harbor version in range (#653)
  apis/goharbor.io/v1alpha3/harbor_types.go
  apis/goharbor.io/v1alpha3/harbor_webhook.go
  apis/goharbor.io/v1alpha3/harborcluster_types.go
  apis/goharbor.io/v1alpha3/harborcluster_webhook.go
  config/samples/harborcluster-minimal/goharbor_v1alpha3_harbor.yaml
  controllers/goharbor/chartmuseum/chartmuseum_test.go
  controllers/goharbor/chartmuseum_test.go
  controllers/goharbor/core/core_test.go
  controllers/goharbor/core_test.go
  controllers/goharbor/exporter_test.go
  controllers/goharbor/harbor/manifests/jobservice/default-expected.yaml
  controllers/goharbor/harbor/manifests/jobservice/default.yaml
  controllers/goharbor/harbor/manifests/jobservice/repository-and-tag-suffix-not-empty-expected.yaml
  controllers/goharbor/harbor/manifests/jobservice/repository-and-tag-suffix-not-empty.yaml
  controllers/goharbor/harbor/manifests/jobservice/repository-not-empty-expected.yaml
  controllers/goharbor/harbor/manifests/jobservice/repository-not-empty.yaml
  controllers/goharbor/harbor/manifests/jobservice/tag-suffix-not-empty-expected.yaml
  controllers/goharbor/harbor/manifests/jobservice/tag-suffix-not-empty.yaml
  controllers/goharbor/harbor_test.go
  controllers/goharbor/internal/test/utils.go
  controllers/goharbor/jobservice/jobservice_test.go
  controllers/goharbor/jobservice_test.go
  controllers/goharbor/notaryserver/notaryserver_test.go
  controllers/goharbor/notaryserver_test.go
  controllers/goharbor/notarysigner/notarysigner_test.go
  controllers/goharbor/notarysigner_test.go
  controllers/goharbor/portal/portal_test.go
  controllers/goharbor/portal_test.go
  controllers/goharbor/registry/registry_test.go
  controllers/goharbor/registry_test.go
  controllers/goharbor/registryctl/registryctl_test.go
  controllers/goharbor/registryctl_test.go
  controllers/goharbor/trivy/trivy_test.go
  controllers/goharbor/trivy_test.go
  go.mod
  manifests/cluster/deployment.yaml
  manifests/harbor/deployment.yaml
  manifests/samples/full_stack.yaml
  manifests/samples/minimal_stack_fs.yaml
  manifests/samples/minimal_stack_incluster.yaml
  manifests/samples/standard_stack.yaml
  manifests/samples/standard_stack_fs.yaml
  pkg/image/image.go
  pkg/image/image_test.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: release/1.0.1
