Repository goharbor/harbor-operator, pull requests merged in 2021-04, with the labels that each got.

#577 fix: correct the resource limits for the postgres
  pkg/cluster/controllers/database/utils.go
Labels: release/1.0

#575 Make PostgreSQL secrets name template configurable
  pkg/cluster/controllers/database/readiness.go
Labels: dependency/database

#618 doc(console):add doc for enabling minio console
  README.md
  docs/configurations/operator-configurations.md
  docs/images/console/dashboard.png
  docs/images/console/login.png
  docs/installation/by-helm-chart.md
  docs/installation/enable_minio_console.md
  docs/installation/kustomization-all-in-one.md
  docs/installation/kustomization-custom.md
  docs/makefile.md
Labels: release/1.0

#621 docs: add doc about upgrade harbor cluster
  docs/LCM/upgrade-cluster.md
Labels: documentation, release/1.0

#623 doc(installation):add doc for custimizing storage,db and cache
  README.md
  docs/installation/customize-storage-db-redis.md
  docs/tutorial.md
Labels: area/samples, documentation, release/1.0

#624 fix(samples):revise errors in sample manifest
  manifests/samples/standard_stack.yaml
Labels: area/samples, release/1.0
